export const ADMINISTRATION_BASE_PATH = 'administration';
export const BLACKLISTDEVICE_BASE_PATH =
  ADMINISTRATION_BASE_PATH + '/blackListDevice';
export const BLACKLISTDEVICE_PATHS = {
  LIST_BLACKLISTDEVICE: '',
};
export const BLACKLISTDEVICE_PATHS_WITH_BASE = {
  LIST_BLACKLISTDEVICE:
    BLACKLISTDEVICE_BASE_PATH + '/' + BLACKLISTDEVICE_BASE_PATH,
};

export const WEB_PAY_BASE_PATH = ADMINISTRATION_BASE_PATH + '/webPay';

export const WEB_PAY_PATHS = {
  DETAIL_WEBPAY: 'webPay-details',
  WITH_ID: ':id',
  LIST_WEB_PAY: '',
};

export const WEB_PAY_PATHS_WITH_BASE = {
  LIST_WEB_PAY: WEB_PAY_BASE_PATH,
};
export const CONTRACTS_BASE_PATH = ADMINISTRATION_BASE_PATH + '/contrats';

export const CONTRACTS_PATHS = {
  SUSPEND_CONTRACT: '',
};

export const CONTRACTS_PATHS_WITH_BASE = {
  BASE: '/' + CONTRACTS_BASE_PATH,
  SUSPEND_CONTRACT:
    '/' + CONTRACTS_BASE_PATH + '/' + CONTRACTS_PATHS.SUSPEND_CONTRACT,
};

export const BANKS_CODE_BASE_PATH = ADMINISTRATION_BASE_PATH + '/code-banque';

export const BANKS_CODE_PATHS = {
  LIST_BANKS_CODE: '',
};
export const BANKS_CODE_PATHS_WITH_BASE = {
  BASE: '/' + BANKS_CODE_BASE_PATH,
  LIST_BANK_CODES:
    '/' + BANKS_CODE_BASE_PATH + '/' + BANKS_CODE_PATHS.LIST_BANKS_CODE,
};

export const BLOCK_USER_BASE_PATH =
  ADMINISTRATION_BASE_PATH + '/' + 'bloquer-intervenant';

export const BLOCK_USER_PATHS = {
  BLOCK_USERS: '',
};

export const BLOCK_USER_PATHS_WITH_BASE = {
  BASE: '/' + BLOCK_USER_BASE_PATH,
  BLOCK_USERS: '/' + BLOCK_USER_BASE_PATH + '/' + BLOCK_USER_PATHS.BLOCK_USERS,
};
export const SEND_LOGIN_BASE_PATH = ADMINISTRATION_BASE_PATH + '/sendLogin';

export const SEND_LOGIN_PATHS = {
  SEND_LOGIN: '',
};
export const PISTE_AUDIT_BASE_PATH = ADMINISTRATION_BASE_PATH + '/pisteAudit';

export const PISTE_AUDIT_PATHS = {
  PISTE_AUDIT_LIST: '',
};

export const PISTE_AUDIT_PATHS_WITH_BASE = {
  BASE: '/' + PISTE_AUDIT_BASE_PATH,
  PISTE_AUDIT_LIST:
    '/' + PISTE_AUDIT_BASE_PATH + '/' + PISTE_AUDIT_PATHS.PISTE_AUDIT_LIST,
};
export const VERSIONNING_BASE_PATH =
  ADMINISTRATION_BASE_PATH + '/' + 'versionning';

export const VERSIONNING_PATHS = {
  VERSIONNING_LIST: '',
  ADD_VERSIONNING: 'ajouter-versionning',
  UPDATE_VERSIONNING: 'modifier-versionning',
  VERSIONNING_MBK: 'mbk',
  WITH_APPLICATION: ':app',
  WITH_OS: ':os',
  WITH_ID: ':id',
};

export const VERSIONNING_PATHS_WITH_BASE = {
  BASE: '/' + VERSIONNING_BASE_PATH,
  VERSIONNING_LIST:
    '/' + VERSIONNING_BASE_PATH + '/' + VERSIONNING_PATHS.VERSIONNING_LIST,
  ADD_VERSIONNING:
    '/' + VERSIONNING_BASE_PATH + '/' + VERSIONNING_PATHS.ADD_VERSIONNING,
  UPDATE_VERSIONNING:
    '/' +
    VERSIONNING_BASE_PATH +
    '/' +
    VERSIONNING_PATHS.UPDATE_VERSIONNING +
    '/' +
    VERSIONNING_PATHS.WITH_ID,
  VERSIONNING_MBK:
    '/' +
    VERSIONNING_BASE_PATH +
    '/' +
    VERSIONNING_PATHS.VERSIONNING_MBK +
    '/' +
    VERSIONNING_PATHS.WITH_APPLICATION +
    '/' +
    VERSIONNING_PATHS.WITH_OS,
};
